### PR TITLE
translate Gogs website in french

### PR DESCRIPTION
**Pull request by ghost**
I translate the Gogs website in french

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks a lot!

**Comment by Unknwon** [comment]
I've updated site as well: http://gogs.io/

**Comment by EdzeronK** [comment]
Cool, I translate documentation now.

**Comment by Unknwon** [comment]
@EdzeronK appreciate!

But it's kind of hard for you to keep track of documentation updates. :flushed:

**Pull request merged**
